name: CMake Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ${{ matrix.compiler }}

    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}++

    - name: Build
      working-directory: ./build
      run: cmake --build . --config ${{ env.BUILD_TYPE }} --parallel 2

    - name: Run Hello World Test
      working-directory: ./build
      run: |
        ./hello_world_application/hello_world | grep -q "hello, world!"
        echo "Hello World test passed!"

    - name: Run Solver Test
      working-directory: ./build
      run: |
        echo "Testing equation solver:"
        OUTPUT=$(./solver_application/solve <<< "1 -3 2")
        echo "$OUTPUT"
        echo "$OUTPUT" | grep -q "x1 = 1.000000"
        echo "$OUTPUT" | grep -q "x2 = 2.000000"
        echo "Solver test passed!"

    - name: Run Error Case Test
      working-directory: ./build
      run: |
        echo "Testing error handling:"
        OUTPUT=$(./solver_application/solve <<< "1 1 1")
        echo "$OUTPUT"
        echo "$OUTPUT" | grep -q "no real roots"
        echo "Error test passed!"
