name: CMake Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Create Build Directory
      run: mkdir -p build

    - name: Configure CMake
      working-directory: ./build
      run: cmake .. -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: ./build
      run: cmake --build . --config Release

    - name: Run tests
      working-directory: ./build
      run: |
        ./hello_world_application/hello_world
        ./solver_application/solve <<< "1 -3 2"
